// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgLocalExecution } from "./types/nftvault/nftvault/tx";
import { MsgSendRequestTransferFt } from "./types/nftvault/nftvault/tx";
import { MsgSendRequestTransferNft } from "./types/nftvault/nftvault/tx";
import { MsgRequestTransfer } from "./types/nftvault/nftvault/tx";


export { MsgLocalExecution, MsgSendRequestTransferFt, MsgSendRequestTransferNft, MsgRequestTransfer };

type sendMsgLocalExecutionParams = {
  value: MsgLocalExecution,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendRequestTransferFtParams = {
  value: MsgSendRequestTransferFt,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendRequestTransferNftParams = {
  value: MsgSendRequestTransferNft,
  fee?: StdFee,
  memo?: string
};

type sendMsgRequestTransferParams = {
  value: MsgRequestTransfer,
  fee?: StdFee,
  memo?: string
};


type msgLocalExecutionParams = {
  value: MsgLocalExecution,
};

type msgSendRequestTransferFtParams = {
  value: MsgSendRequestTransferFt,
};

type msgSendRequestTransferNftParams = {
  value: MsgSendRequestTransferNft,
};

type msgRequestTransferParams = {
  value: MsgRequestTransfer,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgLocalExecution({ value, fee, memo }: sendMsgLocalExecutionParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgLocalExecution: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgLocalExecution({ value: MsgLocalExecution.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgLocalExecution: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendRequestTransferFt({ value, fee, memo }: sendMsgSendRequestTransferFtParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendRequestTransferFt: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendRequestTransferFt({ value: MsgSendRequestTransferFt.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendRequestTransferFt: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendRequestTransferNft({ value, fee, memo }: sendMsgSendRequestTransferNftParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendRequestTransferNft: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendRequestTransferNft({ value: MsgSendRequestTransferNft.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendRequestTransferNft: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRequestTransfer({ value, fee, memo }: sendMsgRequestTransferParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRequestTransfer: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRequestTransfer({ value: MsgRequestTransfer.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRequestTransfer: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgLocalExecution({ value }: msgLocalExecutionParams): EncodeObject {
			try {
				return { typeUrl: "/nftvault.nftvault.MsgLocalExecution", value: MsgLocalExecution.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgLocalExecution: Could not create message: ' + e.message)
			}
		},
		
		msgSendRequestTransferFt({ value }: msgSendRequestTransferFtParams): EncodeObject {
			try {
				return { typeUrl: "/nftvault.nftvault.MsgSendRequestTransferFt", value: MsgSendRequestTransferFt.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendRequestTransferFt: Could not create message: ' + e.message)
			}
		},
		
		msgSendRequestTransferNft({ value }: msgSendRequestTransferNftParams): EncodeObject {
			try {
				return { typeUrl: "/nftvault.nftvault.MsgSendRequestTransferNft", value: MsgSendRequestTransferNft.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendRequestTransferNft: Could not create message: ' + e.message)
			}
		},
		
		msgRequestTransfer({ value }: msgRequestTransferParams): EncodeObject {
			try {
				return { typeUrl: "/nftvault.nftvault.MsgRequestTransfer", value: MsgRequestTransfer.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRequestTransfer: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			NftvaultNftvault: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;