// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftvault/nftvault/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAllowedChannelRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
}

func (m *QueryGetAllowedChannelRequest) Reset()         { *m = QueryGetAllowedChannelRequest{} }
func (m *QueryGetAllowedChannelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllowedChannelRequest) ProtoMessage()    {}
func (*QueryGetAllowedChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{2}
}
func (m *QueryGetAllowedChannelRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllowedChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllowedChannelRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllowedChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllowedChannelRequest.Merge(m, src)
}
func (m *QueryGetAllowedChannelRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllowedChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllowedChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllowedChannelRequest proto.InternalMessageInfo

func (m *QueryGetAllowedChannelRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type QueryGetAllowedChannelResponse struct {
	AllowedChannel AllowedChannel `protobuf:"bytes,1,opt,name=allowedChannel,proto3" json:"allowedChannel"`
}

func (m *QueryGetAllowedChannelResponse) Reset()         { *m = QueryGetAllowedChannelResponse{} }
func (m *QueryGetAllowedChannelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllowedChannelResponse) ProtoMessage()    {}
func (*QueryGetAllowedChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{3}
}
func (m *QueryGetAllowedChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllowedChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllowedChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllowedChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllowedChannelResponse.Merge(m, src)
}
func (m *QueryGetAllowedChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllowedChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllowedChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllowedChannelResponse proto.InternalMessageInfo

func (m *QueryGetAllowedChannelResponse) GetAllowedChannel() AllowedChannel {
	if m != nil {
		return m.AllowedChannel
	}
	return AllowedChannel{}
}

type QueryAllAllowedChannelRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAllowedChannelRequest) Reset()         { *m = QueryAllAllowedChannelRequest{} }
func (m *QueryAllAllowedChannelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAllowedChannelRequest) ProtoMessage()    {}
func (*QueryAllAllowedChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{4}
}
func (m *QueryAllAllowedChannelRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAllowedChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAllowedChannelRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAllowedChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAllowedChannelRequest.Merge(m, src)
}
func (m *QueryAllAllowedChannelRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAllowedChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAllowedChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAllowedChannelRequest proto.InternalMessageInfo

func (m *QueryAllAllowedChannelRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAllowedChannelResponse struct {
	AllowedChannel []AllowedChannel    `protobuf:"bytes,1,rep,name=allowedChannel,proto3" json:"allowedChannel"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAllowedChannelResponse) Reset()         { *m = QueryAllAllowedChannelResponse{} }
func (m *QueryAllAllowedChannelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAllowedChannelResponse) ProtoMessage()    {}
func (*QueryAllAllowedChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{5}
}
func (m *QueryAllAllowedChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAllowedChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAllowedChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAllowedChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAllowedChannelResponse.Merge(m, src)
}
func (m *QueryAllAllowedChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAllowedChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAllowedChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAllowedChannelResponse proto.InternalMessageInfo

func (m *QueryAllAllowedChannelResponse) GetAllowedChannel() []AllowedChannel {
	if m != nil {
		return m.AllowedChannel
	}
	return nil
}

func (m *QueryAllAllowedChannelResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryVaultAccountAddressRequest struct {
	ClassId string `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	NftId   string `protobuf:"bytes,2,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
}

func (m *QueryVaultAccountAddressRequest) Reset()         { *m = QueryVaultAccountAddressRequest{} }
func (m *QueryVaultAccountAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVaultAccountAddressRequest) ProtoMessage()    {}
func (*QueryVaultAccountAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{6}
}
func (m *QueryVaultAccountAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVaultAccountAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVaultAccountAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVaultAccountAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVaultAccountAddressRequest.Merge(m, src)
}
func (m *QueryVaultAccountAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVaultAccountAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVaultAccountAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVaultAccountAddressRequest proto.InternalMessageInfo

func (m *QueryVaultAccountAddressRequest) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *QueryVaultAccountAddressRequest) GetNftId() string {
	if m != nil {
		return m.NftId
	}
	return ""
}

type QueryVaultAccountAddressResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryVaultAccountAddressResponse) Reset()         { *m = QueryVaultAccountAddressResponse{} }
func (m *QueryVaultAccountAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVaultAccountAddressResponse) ProtoMessage()    {}
func (*QueryVaultAccountAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d245f08f00c0c93, []int{7}
}
func (m *QueryVaultAccountAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVaultAccountAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVaultAccountAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVaultAccountAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVaultAccountAddressResponse.Merge(m, src)
}
func (m *QueryVaultAccountAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVaultAccountAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVaultAccountAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVaultAccountAddressResponse proto.InternalMessageInfo

func (m *QueryVaultAccountAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "nftvault.nftvault.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "nftvault.nftvault.QueryParamsResponse")
	proto.RegisterType((*QueryGetAllowedChannelRequest)(nil), "nftvault.nftvault.QueryGetAllowedChannelRequest")
	proto.RegisterType((*QueryGetAllowedChannelResponse)(nil), "nftvault.nftvault.QueryGetAllowedChannelResponse")
	proto.RegisterType((*QueryAllAllowedChannelRequest)(nil), "nftvault.nftvault.QueryAllAllowedChannelRequest")
	proto.RegisterType((*QueryAllAllowedChannelResponse)(nil), "nftvault.nftvault.QueryAllAllowedChannelResponse")
	proto.RegisterType((*QueryVaultAccountAddressRequest)(nil), "nftvault.nftvault.QueryVaultAccountAddressRequest")
	proto.RegisterType((*QueryVaultAccountAddressResponse)(nil), "nftvault.nftvault.QueryVaultAccountAddressResponse")
}

func init() { proto.RegisterFile("nftvault/nftvault/query.proto", fileDescriptor_4d245f08f00c0c93) }

var fileDescriptor_4d245f08f00c0c93 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xc7, 0xb3, 0xf9, 0xfd, 0x92, 0xda, 0x47, 0x28, 0x74, 0x5a, 0xa1, 0x89, 0xed, 0xb6, 0x5d,
	0xb4, 0x2d, 0x39, 0xec, 0xe6, 0x0f, 0xe8, 0x45, 0x0f, 0xa9, 0x60, 0xc9, 0x45, 0x6b, 0x04, 0x0f,
	0x5e, 0xc2, 0x24, 0x3b, 0x59, 0x03, 0xdb, 0x99, 0x4d, 0x66, 0x52, 0xad, 0xe2, 0xc5, 0xbb, 0x20,
	0xf8, 0x16, 0xbc, 0x0a, 0x9e, 0x7d, 0x05, 0x3d, 0x16, 0xbc, 0x78, 0x12, 0x49, 0x7c, 0x21, 0x92,
	0x99, 0xd9, 0xc4, 0x35, 0x3b, 0x0d, 0xc5, 0xcb, 0x32, 0x3b, 0xcf, 0xf3, 0xfd, 0x3e, 0x9f, 0xd9,
	0xe7, 0x99, 0x85, 0x2d, 0xda, 0x15, 0xa7, 0x78, 0x18, 0x0a, 0x6f, 0xba, 0xe8, 0x0f, 0xc9, 0xe0,
	0xcc, 0x8d, 0x06, 0x4c, 0x30, 0xb4, 0x1a, 0xef, 0xba, 0xf1, 0xa2, 0xb8, 0x1e, 0xb0, 0x80, 0xc9,
	0xa8, 0x37, 0x59, 0xa9, 0xc4, 0xe2, 0x66, 0xc0, 0x58, 0x10, 0x12, 0x0f, 0x47, 0x3d, 0x0f, 0x53,
	0xca, 0x04, 0x16, 0x3d, 0x46, 0xb9, 0x8e, 0x96, 0x3a, 0x8c, 0x9f, 0x30, 0xee, 0xb5, 0x31, 0x27,
	0xca, 0xdf, 0x3b, 0xad, 0xb4, 0x89, 0xc0, 0x15, 0x2f, 0xc2, 0x41, 0x8f, 0xca, 0x64, 0x9d, 0x6b,
	0xcf, 0x13, 0x45, 0x78, 0x80, 0x4f, 0x62, 0xaf, 0xfd, 0xf9, 0x38, 0x0e, 0x43, 0xf6, 0x92, 0xf8,
	0xad, 0xce, 0x0b, 0x4c, 0x29, 0x09, 0x55, 0xa2, 0xb3, 0x0e, 0xe8, 0xc9, 0xa4, 0xd4, 0xb1, 0x54,
	0x37, 0x49, 0x7f, 0x48, 0xb8, 0x70, 0x1e, 0xc1, 0x5a, 0x62, 0x97, 0x47, 0x8c, 0x72, 0x82, 0xee,
	0x42, 0x5e, 0x55, 0xd9, 0xb0, 0x76, 0xac, 0x83, 0xeb, 0xd5, 0x82, 0x3b, 0x77, 0x72, 0x57, 0x49,
	0x0e, 0xff, 0x3f, 0xff, 0xb1, 0x9d, 0x69, 0xea, 0x74, 0xe7, 0x3e, 0x6c, 0x49, 0xbf, 0x23, 0x22,
	0xea, 0x0a, 0xe3, 0x81, 0xa2, 0xd0, 0x05, 0xd1, 0x26, 0x2c, 0x6b, 0xae, 0x86, 0x2f, 0xcd, 0x97,
	0x9b, 0xb3, 0x0d, 0xa7, 0x0f, 0xb6, 0x49, 0xae, 0xc9, 0x1e, 0xc3, 0x0a, 0x4e, 0x44, 0x34, 0xe1,
	0x6e, 0x0a, 0x61, 0xd2, 0x42, 0x93, 0xfe, 0x25, 0x77, 0x02, 0x4d, 0x5c, 0x0f, 0xc3, 0x74, 0xe2,
	0x87, 0x00, 0xb3, 0xae, 0xe8, 0x6a, 0x7b, 0xae, 0x6a, 0xa1, 0x3b, 0x69, 0xa1, 0xab, 0x46, 0x44,
	0xb7, 0xd0, 0x3d, 0xc6, 0x01, 0xd1, 0xda, 0xe6, 0x1f, 0x4a, 0xe7, 0xab, 0xa5, 0x0f, 0x97, 0x52,
	0xe9, 0x92, 0xc3, 0xfd, 0xf7, 0x0f, 0x87, 0x43, 0x47, 0x09, 0xf6, 0xac, 0x64, 0xdf, 0x5f, 0xc8,
	0xae, 0x68, 0x12, 0xf0, 0x4f, 0x61, 0x5b, 0xb2, 0x3f, 0x9b, 0xd4, 0xae, 0x77, 0x3a, 0x6c, 0x48,
	0x45, 0xdd, 0xf7, 0x07, 0x84, 0xc7, 0xa3, 0x84, 0x0a, 0x70, 0xad, 0x13, 0x62, 0xce, 0x5b, 0xbd,
	0xb8, 0xb1, 0x4b, 0xf2, 0xbd, 0xe1, 0xa3, 0x1b, 0x90, 0xa7, 0x5d, 0x31, 0x09, 0x64, 0x65, 0x20,
	0x47, 0xbb, 0xa2, 0xe1, 0x3b, 0xf7, 0x60, 0xc7, 0x6c, 0xaa, 0x3f, 0xc9, 0x06, 0x2c, 0x61, 0xb5,
	0x15, 0x9b, 0xea, 0xd7, 0xea, 0xfb, 0x1c, 0xe4, 0xa4, 0x1c, 0xbd, 0x86, 0xbc, 0x1a, 0x46, 0x74,
	0x3b, 0xe5, 0x43, 0xcd, 0x4f, 0x7d, 0x71, 0x6f, 0x51, 0x9a, 0x2a, 0xee, 0xec, 0xbe, 0xfb, 0xf6,
	0xeb, 0x63, 0xf6, 0x26, 0x2a, 0x78, 0xa6, 0x5b, 0x88, 0x3e, 0x5b, 0xb0, 0x92, 0x6c, 0x05, 0x2a,
	0x9b, 0xdc, 0x4d, 0x97, 0xa2, 0x58, 0xb9, 0x82, 0x42, 0xa3, 0xdd, 0x91, 0x68, 0x65, 0xe4, 0x7a,
	0x0b, 0x7f, 0x00, 0xde, 0x9b, 0xe9, 0x05, 0x7b, 0x8b, 0x3e, 0x59, 0xb0, 0x9a, 0xb4, 0xac, 0x87,
	0x97, 0x20, 0x9b, 0x6e, 0x85, 0x19, 0xd9, 0x38, 0xdd, 0x4e, 0x49, 0x22, 0xdf, 0x42, 0xce, 0x62,
	0x64, 0xf4, 0xc5, 0x82, 0xb5, 0x94, 0xb1, 0x40, 0x55, 0x53, 0x59, 0xf3, 0x60, 0x16, 0x6b, 0x57,
	0xd2, 0x68, 0xd8, 0xb2, 0x84, 0x2d, 0xa1, 0x83, 0x14, 0x58, 0xf9, 0x6c, 0x61, 0x25, 0x6c, 0xe9,
	0x79, 0x3c, 0xac, 0x9d, 0x8f, 0x6c, 0xeb, 0x62, 0x64, 0x5b, 0x3f, 0x47, 0xb6, 0xf5, 0x61, 0x6c,
	0x67, 0x2e, 0xc6, 0x76, 0xe6, 0xfb, 0xd8, 0xce, 0x3c, 0x2f, 0x4c, 0x95, 0xaf, 0x66, 0x26, 0xe2,
	0x2c, 0x22, 0xbc, 0x9d, 0x97, 0x3f, 0xe7, 0xda, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x5e,
	0xbd, 0x51, 0x79, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a AllowedChannel by index.
	AllowedChannel(ctx context.Context, in *QueryGetAllowedChannelRequest, opts ...grpc.CallOption) (*QueryGetAllowedChannelResponse, error)
	// Queries a list of AllowedChannel items.
	AllowedChannelAll(ctx context.Context, in *QueryAllAllowedChannelRequest, opts ...grpc.CallOption) (*QueryAllAllowedChannelResponse, error)
	// Queries a list of VaultAccountAddress items.
	VaultAccountAddress(ctx context.Context, in *QueryVaultAccountAddressRequest, opts ...grpc.CallOption) (*QueryVaultAccountAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllowedChannel(ctx context.Context, in *QueryGetAllowedChannelRequest, opts ...grpc.CallOption) (*QueryGetAllowedChannelResponse, error) {
	out := new(QueryGetAllowedChannelResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Query/AllowedChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllowedChannelAll(ctx context.Context, in *QueryAllAllowedChannelRequest, opts ...grpc.CallOption) (*QueryAllAllowedChannelResponse, error) {
	out := new(QueryAllAllowedChannelResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Query/AllowedChannelAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VaultAccountAddress(ctx context.Context, in *QueryVaultAccountAddressRequest, opts ...grpc.CallOption) (*QueryVaultAccountAddressResponse, error) {
	out := new(QueryVaultAccountAddressResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Query/VaultAccountAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a AllowedChannel by index.
	AllowedChannel(context.Context, *QueryGetAllowedChannelRequest) (*QueryGetAllowedChannelResponse, error)
	// Queries a list of AllowedChannel items.
	AllowedChannelAll(context.Context, *QueryAllAllowedChannelRequest) (*QueryAllAllowedChannelResponse, error)
	// Queries a list of VaultAccountAddress items.
	VaultAccountAddress(context.Context, *QueryVaultAccountAddressRequest) (*QueryVaultAccountAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AllowedChannel(ctx context.Context, req *QueryGetAllowedChannelRequest) (*QueryGetAllowedChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowedChannel not implemented")
}
func (*UnimplementedQueryServer) AllowedChannelAll(ctx context.Context, req *QueryAllAllowedChannelRequest) (*QueryAllAllowedChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowedChannelAll not implemented")
}
func (*UnimplementedQueryServer) VaultAccountAddress(ctx context.Context, req *QueryVaultAccountAddressRequest) (*QueryVaultAccountAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VaultAccountAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllowedChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllowedChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllowedChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Query/AllowedChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllowedChannel(ctx, req.(*QueryGetAllowedChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllowedChannelAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAllowedChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllowedChannelAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Query/AllowedChannelAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllowedChannelAll(ctx, req.(*QueryAllAllowedChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VaultAccountAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVaultAccountAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VaultAccountAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Query/VaultAccountAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VaultAccountAddress(ctx, req.(*QueryVaultAccountAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nftvault.nftvault.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AllowedChannel",
			Handler:    _Query_AllowedChannel_Handler,
		},
		{
			MethodName: "AllowedChannelAll",
			Handler:    _Query_AllowedChannelAll_Handler,
		},
		{
			MethodName: "VaultAccountAddress",
			Handler:    _Query_VaultAccountAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nftvault/nftvault/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAllowedChannelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllowedChannelRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllowedChannelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllowedChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllowedChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllowedChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AllowedChannel.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAllowedChannelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAllowedChannelRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAllowedChannelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAllowedChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAllowedChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAllowedChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AllowedChannel) > 0 {
		for iNdEx := len(m.AllowedChannel) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedChannel[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryVaultAccountAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVaultAccountAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVaultAccountAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftId) > 0 {
		i -= len(m.NftId)
		copy(dAtA[i:], m.NftId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NftId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVaultAccountAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVaultAccountAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVaultAccountAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAllowedChannelRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllowedChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AllowedChannel.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAllowedChannelRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAllowedChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AllowedChannel) > 0 {
		for _, e := range m.AllowedChannel {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVaultAccountAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.NftId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVaultAccountAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllowedChannelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllowedChannelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllowedChannelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllowedChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllowedChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllowedChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedChannel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AllowedChannel.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAllowedChannelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAllowedChannelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAllowedChannelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAllowedChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAllowedChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAllowedChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedChannel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedChannel = append(m.AllowedChannel, AllowedChannel{})
			if err := m.AllowedChannel[len(m.AllowedChannel)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVaultAccountAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVaultAccountAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVaultAccountAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVaultAccountAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVaultAccountAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVaultAccountAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
