// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftvault/nftvault/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLocalExecution struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgLocalExecution) Reset()         { *m = MsgLocalExecution{} }
func (m *MsgLocalExecution) String() string { return proto.CompactTextString(m) }
func (*MsgLocalExecution) ProtoMessage()    {}
func (*MsgLocalExecution) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{0}
}
func (m *MsgLocalExecution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLocalExecution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLocalExecution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLocalExecution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLocalExecution.Merge(m, src)
}
func (m *MsgLocalExecution) XXX_Size() int {
	return m.Size()
}
func (m *MsgLocalExecution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLocalExecution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLocalExecution proto.InternalMessageInfo

func (m *MsgLocalExecution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgLocalExecutionResponse struct {
}

func (m *MsgLocalExecutionResponse) Reset()         { *m = MsgLocalExecutionResponse{} }
func (m *MsgLocalExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLocalExecutionResponse) ProtoMessage()    {}
func (*MsgLocalExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{1}
}
func (m *MsgLocalExecutionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLocalExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLocalExecutionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLocalExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLocalExecutionResponse.Merge(m, src)
}
func (m *MsgLocalExecutionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLocalExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLocalExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLocalExecutionResponse proto.InternalMessageInfo

type MsgRequestTransfer struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgRequestTransfer) Reset()         { *m = MsgRequestTransfer{} }
func (m *MsgRequestTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgRequestTransfer) ProtoMessage()    {}
func (*MsgRequestTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{2}
}
func (m *MsgRequestTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestTransfer.Merge(m, src)
}
func (m *MsgRequestTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestTransfer proto.InternalMessageInfo

func (m *MsgRequestTransfer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgRequestTransferResponse struct {
}

func (m *MsgRequestTransferResponse) Reset()         { *m = MsgRequestTransferResponse{} }
func (m *MsgRequestTransferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestTransferResponse) ProtoMessage()    {}
func (*MsgRequestTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{3}
}
func (m *MsgRequestTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestTransferResponse.Merge(m, src)
}
func (m *MsgRequestTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestTransferResponse proto.InternalMessageInfo

type MsgSendRequestTransferFt struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Port             string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ChannelID        string `protobuf:"bytes,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TimeoutTimestamp uint64 `protobuf:"varint,4,opt,name=timeoutTimestamp,proto3" json:"timeoutTimestamp,omitempty"`
}

func (m *MsgSendRequestTransferFt) Reset()         { *m = MsgSendRequestTransferFt{} }
func (m *MsgSendRequestTransferFt) String() string { return proto.CompactTextString(m) }
func (*MsgSendRequestTransferFt) ProtoMessage()    {}
func (*MsgSendRequestTransferFt) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{4}
}
func (m *MsgSendRequestTransferFt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendRequestTransferFt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendRequestTransferFt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendRequestTransferFt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendRequestTransferFt.Merge(m, src)
}
func (m *MsgSendRequestTransferFt) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendRequestTransferFt) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendRequestTransferFt.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendRequestTransferFt proto.InternalMessageInfo

func (m *MsgSendRequestTransferFt) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendRequestTransferFt) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MsgSendRequestTransferFt) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *MsgSendRequestTransferFt) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

type MsgSendRequestTransferFtResponse struct {
}

func (m *MsgSendRequestTransferFtResponse) Reset()         { *m = MsgSendRequestTransferFtResponse{} }
func (m *MsgSendRequestTransferFtResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendRequestTransferFtResponse) ProtoMessage()    {}
func (*MsgSendRequestTransferFtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{5}
}
func (m *MsgSendRequestTransferFtResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendRequestTransferFtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendRequestTransferFtResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendRequestTransferFtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendRequestTransferFtResponse.Merge(m, src)
}
func (m *MsgSendRequestTransferFtResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendRequestTransferFtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendRequestTransferFtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendRequestTransferFtResponse proto.InternalMessageInfo

type MsgSendRequestTransferNft struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Port             string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ChannelID        string `protobuf:"bytes,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TimeoutTimestamp uint64 `protobuf:"varint,4,opt,name=timeoutTimestamp,proto3" json:"timeoutTimestamp,omitempty"`
}

func (m *MsgSendRequestTransferNft) Reset()         { *m = MsgSendRequestTransferNft{} }
func (m *MsgSendRequestTransferNft) String() string { return proto.CompactTextString(m) }
func (*MsgSendRequestTransferNft) ProtoMessage()    {}
func (*MsgSendRequestTransferNft) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{6}
}
func (m *MsgSendRequestTransferNft) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendRequestTransferNft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendRequestTransferNft.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendRequestTransferNft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendRequestTransferNft.Merge(m, src)
}
func (m *MsgSendRequestTransferNft) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendRequestTransferNft) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendRequestTransferNft.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendRequestTransferNft proto.InternalMessageInfo

func (m *MsgSendRequestTransferNft) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendRequestTransferNft) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MsgSendRequestTransferNft) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *MsgSendRequestTransferNft) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

type MsgSendRequestTransferNftResponse struct {
}

func (m *MsgSendRequestTransferNftResponse) Reset()         { *m = MsgSendRequestTransferNftResponse{} }
func (m *MsgSendRequestTransferNftResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendRequestTransferNftResponse) ProtoMessage()    {}
func (*MsgSendRequestTransferNftResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_052e47e41f90e43f, []int{7}
}
func (m *MsgSendRequestTransferNftResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendRequestTransferNftResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendRequestTransferNftResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendRequestTransferNftResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendRequestTransferNftResponse.Merge(m, src)
}
func (m *MsgSendRequestTransferNftResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendRequestTransferNftResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendRequestTransferNftResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendRequestTransferNftResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLocalExecution)(nil), "nftvault.nftvault.MsgLocalExecution")
	proto.RegisterType((*MsgLocalExecutionResponse)(nil), "nftvault.nftvault.MsgLocalExecutionResponse")
	proto.RegisterType((*MsgRequestTransfer)(nil), "nftvault.nftvault.MsgRequestTransfer")
	proto.RegisterType((*MsgRequestTransferResponse)(nil), "nftvault.nftvault.MsgRequestTransferResponse")
	proto.RegisterType((*MsgSendRequestTransferFt)(nil), "nftvault.nftvault.MsgSendRequestTransferFt")
	proto.RegisterType((*MsgSendRequestTransferFtResponse)(nil), "nftvault.nftvault.MsgSendRequestTransferFtResponse")
	proto.RegisterType((*MsgSendRequestTransferNft)(nil), "nftvault.nftvault.MsgSendRequestTransferNft")
	proto.RegisterType((*MsgSendRequestTransferNftResponse)(nil), "nftvault.nftvault.MsgSendRequestTransferNftResponse")
}

func init() { proto.RegisterFile("nftvault/nftvault/tx.proto", fileDescriptor_052e47e41f90e43f) }

var fileDescriptor_052e47e41f90e43f = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0x5f, 0xcb, 0x27, 0xbd, 0x0b, 0xb5, 0x03, 0x4a, 0x1a, 0x4b, 0xa8, 0x51, 0xa1,
	0x68, 0x1b, 0xc1, 0xfa, 0x04, 0xa2, 0x82, 0x60, 0xba, 0x88, 0x5d, 0xb9, 0x8b, 0xe9, 0x24, 0x16,
	0xda, 0x99, 0x98, 0xb9, 0x91, 0x16, 0x7c, 0x08, 0xd1, 0x97, 0x72, 0x23, 0x74, 0xe9, 0x52, 0xda,
	0x17, 0x11, 0x02, 0x89, 0x92, 0x3f, 0xd2, 0xae, 0xdc, 0xdd, 0xdc, 0xfc, 0x38, 0xe7, 0x30, 0x1c,
	0x2e, 0xa8, 0xdc, 0xc5, 0x47, 0x3b, 0x1c, 0xe1, 0x71, 0x32, 0xe0, 0xc4, 0xf0, 0x03, 0x81, 0x82,
	0xd6, 0xe2, 0x95, 0x11, 0x0f, 0x7a, 0x07, 0x6a, 0xa6, 0xf4, 0xae, 0x85, 0x63, 0x8f, 0x2e, 0x26,
	0xcc, 0x09, 0x71, 0x28, 0x38, 0x55, 0x60, 0xcd, 0x09, 0x98, 0x8d, 0x22, 0x50, 0x48, 0x93, 0xb4,
	0xaa, 0x56, 0xfc, 0xa9, 0xef, 0x40, 0x3d, 0x83, 0x5b, 0x4c, 0xfa, 0x82, 0x4b, 0xa6, 0x1b, 0x40,
	0x4d, 0xe9, 0x59, 0xec, 0x21, 0x64, 0x12, 0xfb, 0x81, 0xcd, 0xa5, 0xcb, 0x82, 0x5f, 0xc4, 0x1a,
	0xa0, 0x66, 0xf9, 0x44, 0xed, 0x85, 0x80, 0x62, 0x4a, 0xef, 0x86, 0xf1, 0x41, 0x0a, 0xb9, 0xc4,
	0x62, 0x51, 0x4a, 0xa1, 0xe2, 0x8b, 0x00, 0x95, 0x7f, 0xd1, 0x3a, 0x9a, 0x69, 0x03, 0xaa, 0xce,
	0xbd, 0xcd, 0x39, 0x1b, 0x5d, 0x9d, 0x2b, 0xe5, 0xe8, 0xc7, 0xf7, 0x82, 0x1e, 0xc2, 0x26, 0x0e,
	0xc7, 0x4c, 0x84, 0xd8, 0x1f, 0x8e, 0x99, 0x44, 0x7b, 0xec, 0x2b, 0x95, 0x26, 0x69, 0x55, 0xac,
	0xcc, 0x5e, 0xd7, 0xa1, 0x59, 0x94, 0x29, 0x09, 0xfe, 0x4a, 0xa2, 0x47, 0xca, 0x81, 0x7a, 0xee,
	0xdf, 0x25, 0xdf, 0x83, 0xdd, 0xc2, 0x50, 0x71, 0xf4, 0x93, 0xf7, 0x32, 0x94, 0x4d, 0xe9, 0xd1,
	0x01, 0xac, 0xa7, 0x2a, 0xb1, 0x6f, 0x64, 0xba, 0x63, 0x64, 0x9a, 0xa0, 0xb6, 0x97, 0xa1, 0x62,
	0x37, 0xea, 0xc1, 0x46, 0xba, 0x2c, 0x07, 0xf9, 0x02, 0x29, 0x4c, 0xed, 0x2c, 0x85, 0x25, 0x46,
	0x53, 0xd8, 0xca, 0xaf, 0xd1, 0x51, 0xbe, 0x4e, 0x2e, 0xac, 0x76, 0x57, 0x80, 0x13, 0xeb, 0x27,
	0xd8, 0x2e, 0x28, 0x42, 0x7b, 0x69, 0xb9, 0x9e, 0x8b, 0xea, 0xe9, 0x2a, 0x74, 0xec, 0x7e, 0xd6,
	0x7d, 0x9b, 0x6b, 0x64, 0x36, 0xd7, 0xc8, 0xe7, 0x5c, 0x23, 0xcf, 0x0b, 0xad, 0x34, 0x5b, 0x68,
	0xa5, 0x8f, 0x85, 0x56, 0xba, 0xad, 0x27, 0xd7, 0x61, 0xf2, 0xe3, 0x50, 0x4c, 0x7d, 0x26, 0xef,
	0xfe, 0x47, 0xc7, 0xa2, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x33, 0x56, 0x7c, 0x20, 0x4a, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	LocalExecution(ctx context.Context, in *MsgLocalExecution, opts ...grpc.CallOption) (*MsgLocalExecutionResponse, error)
	RequestTransfer(ctx context.Context, in *MsgRequestTransfer, opts ...grpc.CallOption) (*MsgRequestTransferResponse, error)
	SendRequestTransferFt(ctx context.Context, in *MsgSendRequestTransferFt, opts ...grpc.CallOption) (*MsgSendRequestTransferFtResponse, error)
	SendRequestTransferNft(ctx context.Context, in *MsgSendRequestTransferNft, opts ...grpc.CallOption) (*MsgSendRequestTransferNftResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LocalExecution(ctx context.Context, in *MsgLocalExecution, opts ...grpc.CallOption) (*MsgLocalExecutionResponse, error) {
	out := new(MsgLocalExecutionResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Msg/LocalExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestTransfer(ctx context.Context, in *MsgRequestTransfer, opts ...grpc.CallOption) (*MsgRequestTransferResponse, error) {
	out := new(MsgRequestTransferResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Msg/RequestTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendRequestTransferFt(ctx context.Context, in *MsgSendRequestTransferFt, opts ...grpc.CallOption) (*MsgSendRequestTransferFtResponse, error) {
	out := new(MsgSendRequestTransferFtResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Msg/SendRequestTransferFt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendRequestTransferNft(ctx context.Context, in *MsgSendRequestTransferNft, opts ...grpc.CallOption) (*MsgSendRequestTransferNftResponse, error) {
	out := new(MsgSendRequestTransferNftResponse)
	err := c.cc.Invoke(ctx, "/nftvault.nftvault.Msg/SendRequestTransferNft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	LocalExecution(context.Context, *MsgLocalExecution) (*MsgLocalExecutionResponse, error)
	RequestTransfer(context.Context, *MsgRequestTransfer) (*MsgRequestTransferResponse, error)
	SendRequestTransferFt(context.Context, *MsgSendRequestTransferFt) (*MsgSendRequestTransferFtResponse, error)
	SendRequestTransferNft(context.Context, *MsgSendRequestTransferNft) (*MsgSendRequestTransferNftResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LocalExecution(ctx context.Context, req *MsgLocalExecution) (*MsgLocalExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalExecution not implemented")
}
func (*UnimplementedMsgServer) RequestTransfer(ctx context.Context, req *MsgRequestTransfer) (*MsgRequestTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTransfer not implemented")
}
func (*UnimplementedMsgServer) SendRequestTransferFt(ctx context.Context, req *MsgSendRequestTransferFt) (*MsgSendRequestTransferFtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestTransferFt not implemented")
}
func (*UnimplementedMsgServer) SendRequestTransferNft(ctx context.Context, req *MsgSendRequestTransferNft) (*MsgSendRequestTransferNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestTransferNft not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LocalExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLocalExecution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LocalExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Msg/LocalExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LocalExecution(ctx, req.(*MsgLocalExecution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Msg/RequestTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestTransfer(ctx, req.(*MsgRequestTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendRequestTransferFt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendRequestTransferFt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendRequestTransferFt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Msg/SendRequestTransferFt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendRequestTransferFt(ctx, req.(*MsgSendRequestTransferFt))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendRequestTransferNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendRequestTransferNft)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendRequestTransferNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nftvault.nftvault.Msg/SendRequestTransferNft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendRequestTransferNft(ctx, req.(*MsgSendRequestTransferNft))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nftvault.nftvault.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocalExecution",
			Handler:    _Msg_LocalExecution_Handler,
		},
		{
			MethodName: "RequestTransfer",
			Handler:    _Msg_RequestTransfer_Handler,
		},
		{
			MethodName: "SendRequestTransferFt",
			Handler:    _Msg_SendRequestTransferFt_Handler,
		},
		{
			MethodName: "SendRequestTransferNft",
			Handler:    _Msg_SendRequestTransferNft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nftvault/nftvault/tx.proto",
}

func (m *MsgLocalExecution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLocalExecution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLocalExecution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLocalExecutionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLocalExecutionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLocalExecutionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRequestTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSendRequestTransferFt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendRequestTransferFt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendRequestTransferFt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChannelID) > 0 {
		i -= len(m.ChannelID)
		copy(dAtA[i:], m.ChannelID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Port) > 0 {
		i -= len(m.Port)
		copy(dAtA[i:], m.Port)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Port)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendRequestTransferFtResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendRequestTransferFtResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendRequestTransferFtResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSendRequestTransferNft) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendRequestTransferNft) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendRequestTransferNft) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChannelID) > 0 {
		i -= len(m.ChannelID)
		copy(dAtA[i:], m.ChannelID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Port) > 0 {
		i -= len(m.Port)
		copy(dAtA[i:], m.Port)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Port)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendRequestTransferNftResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendRequestTransferNftResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendRequestTransferNftResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLocalExecution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLocalExecutionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRequestTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRequestTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSendRequestTransferFt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	return n
}

func (m *MsgSendRequestTransferFtResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSendRequestTransferNft) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	return n
}

func (m *MsgSendRequestTransferNftResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLocalExecution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLocalExecution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLocalExecution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLocalExecutionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLocalExecutionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLocalExecutionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendRequestTransferFt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendRequestTransferFt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendRequestTransferFt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendRequestTransferFtResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendRequestTransferFtResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendRequestTransferFtResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendRequestTransferNft) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendRequestTransferNft: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendRequestTransferNft: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendRequestTransferNftResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendRequestTransferNftResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendRequestTransferNftResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
